### ISSUE TITLE
无法访问Google

### ISSUE THREAD

**Issue by keywenzhiyuan** [shadowsocks/ShadowsocksX-NG#546] opened 2017-10-11 02:19 UTC
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

 2017-10-10 00:02:34 ERROR: failed to resolve the provided hostname
 2017-10-10 00:02:34 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 00:02:52 ERROR: failed to resolve server name, wait 2 seconds
 2017-10-10 00:17:18 ERROR: failed to resolve server name, wait 4 seconds
 2017-10-10 00:17:42 ERROR: failed to resolve server name, wait 8 seconds
 2017-10-10 00:17:58 ERROR: failed to resolve server name, wait 16 seconds
 2017-10-10 00:18:21 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 00:18:38 ERROR: failed to resolve server name, wait 2 seconds
 2017-10-10 00:18:42 ERROR: failed to resolve server name, wait 4 seconds
 2017-10-10 00:18:50 ERROR: failed to resolve server name, wait 8 seconds
 2017-10-10 00:19:06 ERROR: failed to resolve server name, wait 16 seconds
 2017-10-10 03:19:26 ERROR: failed to resolve server name, wait 32 seconds
 2017-10-10 07:11:14 ERROR: failed to resolve server name, wait 64 seconds
 2017-10-10 09:36:24 ERROR: failed to resolve server name, wait 128 seconds
 2017-10-10 09:36:24 ERROR: getaddrinfo: nodename nor servname provided, or not known
 2017-10-10 09:36:24 ERROR: failed to resolve the provided hostname
 2017-10-10 09:36:24 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 09:36:27 INFO: listening at 127.0.0.1:1086
 2017-10-10 12:27:10 ERROR: connect: Network is down
 2017-10-10 12:27:10 ERROR: connect: Network is down
 2017-10-10 12:27:10 ERROR: connect: Network is down
 2017-10-10 12:32:23 ERROR: connect: Network is down
 2017-10-10 12:32:23 ERROR: connect: Network is down
 2017-10-10 12:32:23 ERROR: connect: Network is down
 2017-10-10 12:32:23 ERROR: connect: Network is down
 2017-10-10 12:32:23 ERROR: connect: Network is down
 2017-10-10 12:36:41 ERROR: connect: Network is down
 2017-10-10 12:36:41 ERROR: connect: Network is down
 2017-10-10 12:36:41 ERROR: connect: Network is down
 2017-10-10 12:36:41 ERROR: connect: Network is down
 2017-10-10 12:40:58 ERROR: connect: Network is down
 2017-10-10 12:40:58 ERROR: connect: Network is down
 2017-10-10 12:40:58 ERROR: connect: Network is down
 2017-10-10 12:40:58 ERROR: connect: Network is down
 2017-10-10 12:45:16 ERROR: connect: Network is down
 2017-10-10 12:45:16 ERROR: connect: Network is down
 2017-10-10 12:45:16 ERROR: connect: Network is down
 2017-10-10 16:01:13 ERROR: getpeername: Invalid argument
 2017-10-10 16:03:19 ERROR: connect: No route to host
 2017-10-10 16:03:19 ERROR: connect: No route to host
 2017-10-10 16:03:22 ERROR: connect: No route to host
 2017-10-10 16:03:22 ERROR: connect: No route to host
 2017-10-10 16:03:35 ERROR: connect: No route to host
 2017-10-10 16:03:35 ERROR: connect: No route to host
 2017-10-10 16:03:35 ERROR: connect: No route to host
 2017-10-10 16:03:43 ERROR: connect: No route to host
 2017-10-10 16:04:07 ERROR: connect: No route to host
 2017-10-10 16:04:07 ERROR: connect: No route to host
 2017-10-10 16:04:07 ERROR: connect: No route to host
 2017-10-10 16:04:31 ERROR: connect: No route to host
2017-10-10 16:05:36 INFO: initialize ciphers... aes-256-cfb
2017-10-10 16:05:36 INFO: tcp port reuse enabled
2017-10-10 16:05:36 INFO: listening at 127.0.0.1:1081
 2017-10-10 16:05:37 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 16:05:45 ERROR: failed to resolve server name, wait 2 seconds
 2017-10-10 16:05:49 ERROR: failed to resolve server name, wait 4 seconds
 2017-10-10 16:05:50 INFO: listening at 127.0.0.1:1086

**Comment by timothyqiu** [comment] 2017-10-11 02:25
> 2017-10-10 16:05:45 ERROR: failed to resolve server name, wait 2 seconds
2017-10-10 16:05:49 ERROR: failed to resolve server name, wait 4 seconds

Possible duplicate of #525 #531

**Comment by keywenzhiyuan** [comment] 2017-10-11 03:24
Can you solve this problem

**Closed** 2017-10-18 04:24 UTC
