### ISSUE TITLE
Crashes of 1.7 on 10.13.2

### ISSUE THREAD

**Issue by Ashlover** [shadowsocks/ShadowsocksX-NG#693] opened 2018-01-12 03:00 UTC
**System and Shadowsocksx-NG version:**

- macOS 10.13.2 High Sierra (16E????)
- Shadowsocksx-NG 1.7.0

**Expected behavior:**
Not crash?

**Actual behavior:**
After adding one of my servers, which I have mistook an SSR server for SS server, it immediately crashed. Then, when I try to open it again, it just crashes after a few seconds.
(N/A for feature requests)

**Steps to reproduce:**
Just open it and delete it and reinstall it and open it again and it always crashes
(N/A for feature requests)

**How often does this happen?**
Every time I open it.
(N/A for feature requests)

**ss-local.log**
 2018-01-12 10:24:09 INFO: initializing ciphers... aes-256-cfb
 2018-01-12 10:24:09 INFO: tcp port reuse enabled
 2018-01-12 10:24:09 INFO: listening at 127.0.0.1:1086
 2018-01-12 10:31:45 INFO: initializing ciphers... aes-256-cfb
 2018-01-12 10:31:45 INFO: tcp port reuse enabled
 2018-01-12 10:31:45 INFO: listening at 127.0.0.1:1086
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:45:50 ERROR: connect: No route to host
 2018-01-12 10:54:10 ERROR: connect: No route to host
 2018-01-12 10:54:10 ERROR: connect: No route to host
 2018-01-12 10:54:10 ERROR: connect: No route to host
 2018-01-12 10:54:22 ERROR: connect: No route to host
 2018-01-12 10:54:39 ERROR: connect: No route to host
 2018-01-12 10:54:41 ERROR: connect: No route to host
 2018-01-12 10:54:42 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:55:33 ERROR: connect: No route to host
 2018-01-12 10:56:00 ERROR: connect: No route to host
 2018-01-12 10:56:00 ERROR: connect: No route to host
 2018-01-12 10:56:00 ERROR: connect: No route to host
 2018-01-12 10:56:01 ERROR: connect: No route to host
 2018-01-12 10:56:01 ERROR: connect: No route to host
 2018-01-12 10:56:01 ERROR: connect: No route to host
 2018-01-12 10:56:03 ERROR: connect: No route to host
 2018-01-12 10:56:03 ERROR: connect: No route to host
 2018-01-12 10:56:03 ERROR: connect: No route to host
 2018-01-12 10:56:04 ERROR: connect: No route to host
 2018-01-12 10:56:04 ERROR: connect: No route to host
 2018-01-12 10:56:04 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:09 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:12 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:13 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:16 ERROR: connect: No route to host
 2018-01-12 10:56:21 ERROR: connect: No route to host
 2018-01-12 10:56:22 ERROR: connect: No route to host
 2018-01-12 10:56:22 ERROR: connect: No route to host
 2018-01-12 10:56:22 ERROR: connect: No route to host

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**
None exists
Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**
Didn't pop up
If the app crashes and pop up a crash log, please copy and paste here

**Comment by qiuyuzhou** [comment] 2018-02-06 09:46
It was caused by ping.
Has been fixed in 1.7.1

**Closed by qiuyuzhou** 2018-02-06 09:46 UTC

**Comment by tmrhjwacd2008** [comment] 2018-11-15 05:32
@qiuyuzhou 嗨，给朋友推荐了这个，但是1.8.2在iMac（10.13.2）依然存在无法打开（崩溃）
Hi, my friends use version 1.8.2 at iMac 10.13.2 got crash when open it everytime.
