### ISSUE TITLE
feature : exclude rules for global mode

### ISSUE THREAD

**Issue by DJafari** [shadowsocks/ShadowsocksX-NG#524] opened 2017-10-07 13:06 UTC
i want a feature, i am a web developer and working with .dev domains in local, when my shadowsocks run in global mode, i can't access to my local domains. i want add a config to exclude it, it can be set in system setting proxy, Bypass proxy setting, but because shadowsocks set it automatically, after restart of shadowsocks it is set to default value

thanks

**Comment by timothyqiu** [comment] 2017-10-08 05:08
Possible duplicate of #494 

A better way of making changes to the system Bypass Proxy Settings might be the solution.

**Comment by DJafari** [comment] 2017-10-08 12:36
@timothyqiu yes, you say right, but after set bypass proxy setting, when shadowsocks off, and again on, bypass setting resets to default value and i must set it after each turning on of shadowsocks

**Closed** 2018-09-17 10:50 UTC
