### ISSUE TITLE
为什么端口必须要一样啊，客户端的端口 必须和KCPTUN一样 一变端口 跟着一起变

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocks/ShadowsocksX-NG#628] opened 2017-11-28 12:21 UTC
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

![qq20171128-202138](https://user-images.githubusercontent.com/6214084/33319455-c22371f8-d479-11e7-8b96-de5c68283a39.png)

**Comment by timothyqiu** [comment] 2017-11-28 14:10
The disabled server port field just means _"please ignore the value here"_, it does not require your `ss-server` to listen on that port.

It's indeed a misleading UI behavior. (Because we're overloading the `serverPort` field.)

Possible duplicate of #513

**Comment by yangfeicheung** [comment] 2017-12-01 15:26
This is a ui bug,when you enable the kcp mode,the server port is actually not used any more, since kcp does all the connection work with the server, I fixed this in this version:

[https://github.com/yangfeicheung/Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X)

**Closed** 2018-09-16 13:42 UTC
